### ISSUE TITLE
ImportError: failed to locate suitable hidapi shared object

### ISSUE THREAD

**Issue by GenNetEng** [JnyJny/blynclight#1]
Afternoon -

While trying to import Blynclight, I get the following Error:

`Python 3.7.0 (default, Aug 17 2018, 21:14:48) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from blynclight import BlyncLight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/blynclight/__init__.py", line 30, in <module>
    from .blynclight import BlyncLight
  File "/usr/local/lib/python3.7/site-packages/blynclight/blynclight.py", line 6, in <module>
    from .hid import enumerate as hid_enumerate
  File "/usr/local/lib/python3.7/site-packages/blynclight/hid/__init__.py", line 48, in <module>
    raise ImportError('failed to locate suitable hidapi shared object')
ImportError: failed to locate suitable hidapi shared object
`

As you might know, I am running Mac OS X with Python3.7.  Also, it doesn't say, but could you post the package dependencies required?  I suspect that may be the issue.

**Comment by JnyJny** [comment]
I did forget a dependency and I'm not quite sure how to specify it wrt to the python packaging. 

For macOS, I used brew to install hidapi:
```
  # brew install hidapi
```
and for CentOS/RedHat derived Linuxes I used:
```
  # yum -y install hidapi
```

That should at least get you started while I figure it out (pull requests accepted ;).

**Comment by JnyJny** [comment]
I think the right answer may be to switch from the HID API to PyUSB.  Neither appear to be actively supported, however PyUSB has seen an update in the last year or so.  I'll have to re-tool some of the USB communication in the implementation, but the API for the light should remain relatively stable.

PyUSB has a proper PyPi entry and appears to do the right thing on macOS and Linux.

**Comment by JnyJny** [comment]
I just pushed a set of changes that rips out HID API support in favor of PyUSB (which is listed as a requisite). It doesn't handle multiple devices opened simultaneously yet, but it seems to handle one just fine.

**Comment by JnyJny** [comment]
Installing in a clean virtual environment on both macOS and Linux results in a complete install of blynclight and it's pre-requisites. I've pushed a new package to PyPi with version 0.3.1 which should solve the issue (prerequisites not installed). @bkcrisler please let me know if this fixes the problem for you.

**Comment by JnyJny** [comment]
Sigh, I'm all alone.  Closing this issue and crying myself to sleep.

**Comment by GenNetEng** [comment]
Sorry. I was able to update to the latest, but it doesn't recognize my
Blynclight.  Maybe the version I have is too old. I no longer have the
import Blynclight issues though.

~~~~~~~~~~~~~~~~~~~~~~~~~
Bryan K. Crisler, Jr.
bkcrisler@gmail.com
~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by JnyJny** [comment]
Well that's a step in the right direction!

Can you post the output of 'system_profiler SPUSBDataType', it might help me identify your light.

**Comment by JnyJny** [comment]
I'm closing this issue since the original problem is fixed, opened a new issue to track the unrecognized light, #4 Light Not Recognized.
