### ISSUE TITLE
[QUESTION] Source of COMMAND_LENGTH

### ISSUE THREAD

**Issue by dend** [JnyJny/blynclight#20]
I see that you are using a constant, called `COMMAND_LENGTH = 9`. Where does this value originate from? As in - how did you come up with the length 9?

**Comment by JnyJny** [comment]
I believe I determined the command length by snooping the usb bus with WireShark and manipulating the light with the Embrava software.

**Comment by dend** [comment]
Interesting. I am going through your code to understand the internals of the process and try to piece together the flow. Will have to fire up WireShark and see what I can get. Appreciate the insights!

**Comment by JnyJny** [comment]
If you have questions about the internals feel free to send me mail directly rather than open an issue every time :)

-ejo
