### ISSUE TITLE
RFE: add a udev rule to docs

### ISSUE THREAD

**Issue by pcfe** [JnyJny/blynclight#21]
Request for enhancement

Can you please add a few lines on udev rules to the readme?
At least on Fedora 32 a user will *not* be allowed to access the blynclight by default.

For my BlyncLight Plus, I created the following rule (`/etc/udev/rules.d/99-blynclight.rules`) to allow all users on this workstation read/write access to the device

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="2c0d", ATTRS{idProduct}=="0010", MODE="0666"
```

If you have a list of all the USB IDs embrave uses, then I can make a PR if wished.

**Comment by JnyJny** [comment]
Thanks, I've stopped working on blynclight for the most part, focusing on [busylight](https://github.com/JnyJny/busylight) which supports more devices than just the Embrava BlyncLight family. Coincidentally, the `busylight` command-line tool has a `dev-rules` sub-command that generates the appropriate udev rules. I'll make the same feature available for `blynclight`.

**Comment by JnyJny** [comment]
Version 0.12.0 has the `dev-rules` command and updated documentation. Re-open if I'm missing any vendor identifiers. Thanks for the enhancement request.

**Comment by pcfe** [comment]
tyvm for the ultra quick implementation of this RFE.
I'll switch to `busylight` now, as suggested. Must have missed that repo in my quick pre-purchase search.

**Comment by JnyJny** [comment]
Out of curiosity, do you recall the search terms you used? It would help me improve my "SEO" for busylight.

**Comment by pcfe** [comment]
> Out of curiosity, do you recall the search terms you used?

digging in my firefox history, it seems to have been:
https://duckduckgo.com/?t=ffab&q=Embrava+Blynclight+Linux&ia=web

>  It would help me improve my "SEO" for busylight.

Yupp, although I guess most users will Google instead of DDG.

I also searched as follows
https://github.com/search?q=blynclight
but somehow overlooked JnyJny/busylight on page 4, that might be related to the description starting with the string "Control Agile Innovations" which I now know is a verb followed by a busylight name, but back then when going through 34 possible repos this was most probably also filed under "marketing BS, next". Might have been better if it was "Control various busylights, vendor A, vendor B, …"

May I suggest also changing "Checkout my latest project, Busylight for Humans™!" in the readme to something more clearly noting that busylight a way more advanced tool that supercedes blynclight.

Maybe it's just me, but I read "Checkout my" and though, yeah advertisement is OK but I'm here to talk to my Blynclight, then my brain skipped over "latest project, Busylight " and at "for Humans™!" I thought "marketing BS, I really just need that thing to light up in 3 colours before I start this work day in earnest." and scrolled down until I found the heading "Installation"

But again, this might just be me.

Suggested text
```
blynclight has been deprecated in favour of [busylight](https://github.com/JnyJny/busylight/).
```

**Comment by JnyJny** [comment]
Thank you very much for the follow up. I have to write stuffy verbiage like that for the day job and sometimes I just gotta be me (even to my detriment it seems).  I'll take your recommendations under advisement and see if I can't find a happy medium that helps potential users find this software easier while still allowing me to laugh. "for Humans™" is from the 2019 April Fools PEP which advised people to write more tools "for Humans™", taking a poke at the Requests project's funny name :)

Thanks again for the feedback, I appreciate it very much!
