### ISSUE TITLE
Light not recognized.

### ISSUE THREAD

**Issue by JnyJny** [JnyJny/blynclight#4]
@bkcrisler said:
> Sorry. I was able to update to the latest, but it doesn't recognize my
> Blynclight.  Maybe the version I have is too old. I no longer have the
> import Blynclight issues though.

Opened a new issue to track this problem.

Please post the output of 'system_profiler SPUSBDataType' here and maybe we can figure out how your light wants to be addressed.

Thanks for you help debugging this!

**Comment by GenNetEng** [comment]
Blynclight:

          Product ID: 0x2517
          Vendor ID: 0x0e53
          Version: 1.00
          Speed: Up to 1.5 Mb/sec
          Location ID: 0x14200000 / 13
          Current Available (mA): 500
          Current Required (mA): 100
          Extra Operating Current (mA): 0

![img_1251](https://user-images.githubusercontent.com/22179713/45708082-2359e980-bb46-11e8-825c-336af18572a9.JPG)

**Comment by GenNetEng** [comment]
I see why its not picking up my Blynclight.  Your Vendor code is different that mine.
In the Code: EMBRAVA_VENDOR_ID=0x2c0d

Mine is 0x0e53

**Comment by JnyJny** [comment]
Sweet, I think I can do something with that.

**Comment by JnyJny** [comment]
I've pushed a fix to the repo but haven't republished the package. Any chance you could clone the repo and test that it's working as intended?

**Comment by JnyJny** [comment]
Pretty sure this is working now, re-open if it's not.
